version: '3.1'
services:
  database:
    image: postgres:16-alpine
    container_name: devops-play-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - PG_USER=postgres
      - TZ=UTC
    ports:
      - 5432:5432
    volumes:
      - ./.db/data:/var/lib/postgresql/data:delegated
      - ./.db/init:/docker-entrypoint-initdb.d
